// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1_rVIKcHSGA9z9Toj2LmROnJV3LyHONM',
    appId: '1:696692161930:web:35d25f4560f6bf96465c73',
    messagingSenderId: '696692161930',
    projectId: 'foodapp-7783a',
    authDomain: 'foodapp-7783a.firebaseapp.com',
    storageBucket: 'foodapp-7783a.appspot.com',
    measurementId: 'G-RKZNNNLBV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiIlmPqrum_aFMDj_TnX1FQTJhEldq0ko',
    appId: '1:696692161930:android:95eba86e2df33ed0465c73',
    messagingSenderId: '696692161930',
    projectId: 'foodapp-7783a',
    storageBucket: 'foodapp-7783a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Q5bNyv7JBHxJK4SFa7QUVJ7Q3UYZweg',
    appId: '1:696692161930:ios:379f0964a6b3cd66465c73',
    messagingSenderId: '696692161930',
    projectId: 'foodapp-7783a',
    storageBucket: 'foodapp-7783a.appspot.com',
    iosBundleId: 'com.example.gourmetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Q5bNyv7JBHxJK4SFa7QUVJ7Q3UYZweg',
    appId: '1:696692161930:ios:379f0964a6b3cd66465c73',
    messagingSenderId: '696692161930',
    projectId: 'foodapp-7783a',
    storageBucket: 'foodapp-7783a.appspot.com',
    iosBundleId: 'com.example.gourmetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1_rVIKcHSGA9z9Toj2LmROnJV3LyHONM',
    appId: '1:696692161930:web:a8efce2f5a31f269465c73',
    messagingSenderId: '696692161930',
    projectId: 'foodapp-7783a',
    authDomain: 'foodapp-7783a.firebaseapp.com',
    storageBucket: 'foodapp-7783a.appspot.com',
    measurementId: 'G-ENFQVLTWD0',
  );
}
